name: reprohackathon
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- bioblend=0.8.0=py36_0
- dropbox=5.2.1=py36_0
- filechunkio=1.6=py36_0
- ftputil=3.2=py36_0
- pysftp=0.2.9=py36_0
- requests-toolbelt=0.5.0=py36_0
- snakemake=3.12.0=py36_1
- urllib3=1.12=py36_0
- asn1crypto=0.22.0=py36_0
- boto=2.46.1=py36_0
- cffi=1.10.0=py36_0
- cryptography=1.8.1=py36_0
- docutils=0.13.1=py36_0
- idna=2.5=py36_0
- openssl=1.0.2l=0
- packaging=16.8=py36_0
- paramiko=2.1.2=py36_0
- pip=9.0.1=py36_1
- psutil=5.2.2=py36_0
- pyasn1=0.2.3=py36_0
- pycparser=2.17=py36_0
- pyparsing=2.1.4=py36_0
- python=3.6.1=2
- pyyaml=3.12=py36_0
- readline=6.2=2
- requests=2.14.2=py36_0
- setuptools=27.2.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- wrapt=1.10.10=py36_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
prefix: /Users/bebatut/miniconda3/envs/reprohackathon

